Implementado copia do app.db para a pasta de publish

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,4 +1,4 @@
-name: Build and Test
+﻿name: Build and Test
 on:
   push:
     branches:
@@ -25,6 +25,9 @@ jobs:
 
       - name: Tests
         run: dotnet test --no-build --configuration Release ./src
+
+      - name: Publish artifact
+        run: dotnet publish --no-build ./src/BugStore.Api/BugStore.Api.csproj --configuration Release --output publish
       
       - name: Install Entity Framework CLI
         run: dotnet tool install --global dotnet-ef
@@ -35,9 +38,12 @@ jobs:
       - name: Entity Framework Update-Database 
         run: dotnet ef database update --no-build --configuration Release --project ./src/BugStore.Api/BugStore.Api.csproj
 
-      - name: Publish artifact
-        run: dotnet publish --no-build ./src/BugStore.Api/BugStore.Api.csproj --configuration Release --output publish
-       
+      - name: Copy SQLite DB to publish folder
+        run: find ./src/BugStore.Api -name "app.db" -exec cp {} ./publish/app.db \; || echo "⚠️ app.db not found!"
+
+      - name: Verify app.db presence before deploy
+        run: ls -la ./publish | grep app.db || (echo "❌ app.db missing!" && exit 1)
+
       - name: Zip published artifact
         run: cd publish && zip -r ../published-app.zip . && cd ..
 
